apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcaresystem
  namespace: default
spec:
  selector:
    matchLabels:
      app: healthcaresystem
  replicas: 1
  template:
    metadata:
      name: healthcaresystem
      labels:
        app: healthcaresystem
    spec:
      containers:
      - name: healthcaresystem
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: eate2020/healthcaresystem:0.0.1