apiVersion: v1
kind: Service
metadata:
  labels:
    app: healthcaresystem
  name: healthcaresystem
spec:
  ports:
    - name: healthcaresystem
      port: 8080
      protocol: TCP
  selector:
    app: healthcaresystem
  type: LoadBalancer